<?php
/**
 * @file
 * Interface module for adding history back button.
 */

/**
 * Implements hook_page_build().
 */
function ding_history_back_page_build(&$page) {
  $paths = array(
    'ting/object',
    'ting/collection',
  );

  $path = current_path();
  $module_path = drupal_get_path('module', 'ding_history_back');

  foreach ($paths as $value) {
    if (strpos($path, $value) === 0) {
      drupal_add_js($module_path . '/js/ding_history_back.js', 'file');
      break;
    }
  }
}
